Repository TeamBeMyPlan/BeMyPlan-Android, pull requests merged in 2022-06, with the labels that each got.

#272 Feature/271
  app/src/main/java/co/kr/bemyplan/data/api/HomeNewService.kt
  app/src/main/java/co/kr/bemyplan/data/api/HomePopularService.kt
  app/src/main/java/co/kr/bemyplan/data/api/HomeSuggestService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LatestListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LocationListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LocationService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LoginService.kt
  app/src/main/java/co/kr/bemyplan/data/api/MoveInfoService.kt
  app/src/main/java/co/kr/bemyplan/data/api/MyPlanService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PlanDetailService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PreviewService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PurchaseService.kt
  app/src/main/java/co/kr/bemyplan/data/api/ScrapListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/ScrapService.kt
  app/src/main/java/co/kr/bemyplan/data/api/SuggestListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/UserPlanListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/WithdrawService.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/viewmodel/AfterPurchaseViewModel.kt
  app/src/main/res/layout/activity_after_purchase.xml
Labels: 💪🏻정훈💪🏻, refactor, connect server

#273 Feature/269
  app/src/main/java/co/kr/bemyplan/data/api/LogoutService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/login/ResponseGoogleLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/logout/RequestSignOut.kt
  app/src/main/java/co/kr/bemyplan/data/entity/logout/ResponseLogout.kt
  app/src/main/java/co/kr/bemyplan/data/entity/logout/ResponseSignOut.kt
  app/src/main/java/co/kr/bemyplan/data/repository/logout/LogoutRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/di/RetrofitModule.kt
  app/src/main/java/co/kr/bemyplan/di/ServiceModule.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/LogoutRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/withdrawal/WithdrawalActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/withdrawal/WithdrawalViewModel.kt
Labels: feat, ✈️승현✈️

#275 Feature/274
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
Labels: feat, ✈️승현✈️

#281 [FEAT] 로그인 및 회원가입 서버통신 Response 수정사항 반영
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/UserInfoResponse.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/login/ResponseLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/signup/ResponseSignUp.kt
  app/src/main/java/co/kr/bemyplan/data/local/BeMyPlanDataStore.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/domain/model/login/UserInfoModel.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/LoginRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckNicknameFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckTermsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewModel.kt
Labels: feat, ✈️승현✈️

#283 [FEAT] 스크랩 여부 체크 API 연결
  app/src/main/java/co/kr/bemyplan/data/api/ScrapService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/scrap/ResponseScrap.kt
  app/src/main/java/co/kr/bemyplan/data/repository/scrap/ScrapRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/ScrapRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
Labels: feat, ✈️승현✈️

#285 [FIX] #282 - endpoint 수정
  app/src/main/java/co/kr/bemyplan/data/api/ScrapService.kt
Labels: bug, ✈️승현✈️

#288 [FIX] QA 반영
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/res/layout/activity_settings.xml
Labels: ✈️승현✈️, QA

#292 [FEAT] #268 마이페이지 UI, 기능(페이징제외) 구현, but.. 제대로 돌아가지만 코드가 뭔가 이상해...
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/res/layout/fragment_my_plan.xml
  build.gradle
Labels: feat, 📸용민🎬

#293 [CHORE] Release config setting
  .gitignore
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: ✈️승현✈️, chore

#294 Feat/268 mypage server
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
Labels: feat, 📸용민🎬, QA

#297 Feature/278
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/after/Images.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/after/Spots.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/viewmodel/AfterPurchaseViewModel.kt
Labels: bug, 💪🏻정훈💪🏻

#298 [feature] #295 - 구매 전 여행일정 미리보기 정보 영문 -> 한글 변경
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewInfo.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewPlan.kt
Labels: feat, ✈️승현✈️

#300 [feature] #299 Firebase Analytics Log Event 설정
  app/src/main/java/co/kr/bemyplan/data/firebase/FirebaseAnalyticsProvider.kt
  app/src/main/java/co/kr/bemyplan/di/SingletonModule.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckEmailFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckNicknameFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/withdrawal/WithdrawalActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment1.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment2.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment3.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/viewmodel/AfterPurchaseViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
Labels: feat, ✈️승현✈️

#301 [feature] #299 DI 모듈 관련 코드 수정
  app/src/main/java/co/kr/bemyplan/data/firebase/FirebaseAnalyticsProvider.kt
  app/src/main/java/co/kr/bemyplan/di/SingletonModule.kt
Labels: feat, ✈️승현✈️

#303 [FEAT] #302 스크랩 탭 무한 스크롤 구현
  app/src/main/java/co/kr/bemyplan/data/api/ScrapListService.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/ScrapListRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/res/layout/fragment_not_empty_scrap.xml
Labels: feat, ✈️승현✈️

#305 [fix] #304 작성자 userId 처리 로직 구현
  app/src/main/java/co/kr/bemyplan/data/api/UserPlanListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/WithdrawService.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
Labels: bug, ✈️승현✈️

#296 [FEAT] #268 마이페이지 무한스크롤 페이지네이션 완료
  app/src/main/java/co/kr/bemyplan/data/api/HomeNewService.kt
  app/src/main/java/co/kr/bemyplan/data/api/HomePopularService.kt
  app/src/main/java/co/kr/bemyplan/data/api/HomeSuggestService.kt
  app/src/main/java/co/kr/bemyplan/data/api/MyPlanService.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/home/HomeNewRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/home/HomePopularRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/home/HomeSuggestRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/HomeNewRepository.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/HomePopularRepository.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/HomeSuggestRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
Labels: feat, 📸용민🎬

#310 Feature/308
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/after/ContentsWithAddress.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/after/MergedPlanAndInfo.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/after/Spots.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/after/SpotsWithAddress.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/viewmodel/AfterPurchaseViewModel.kt
  app/src/main/res/layout/item_daily_contents.xml
  app/src/main/res/layout/item_daily_route.xml
Labels: 💪🏻정훈💪🏻, refactor

#313 Feature/312
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/loading/LoadingDialog.kt
  app/src/main/res/layout/dialog_loading.xml
Labels: feat, 💪🏻정훈💪🏻

#316 Feature/314
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/creator/CreatorProposeActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/viewmodel/AfterPurchaseViewModel.kt
Labels: feat, 💪🏻정훈💪🏻

#319 [FIX] AndroidManifest allowBackup 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/data_extraction_rules.xml
Labels: bug, 🛫승현🛬

#320 [FIX] #317 - 구매 후 여행일정 더미데이터 스크랩 삭제
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
Labels: chore, 💪🏻정훈💪🏻

#322 [FEAT] SortFragment 정렬 기준 수정
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/SortFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/viewmodel/SortViewModel.kt
  app/src/main/java/co/kr/bemyplan/util/BindingAdapter.kt
  app/src/main/res/layout/dialog_sort.xml
Labels: feat, 🛫승현🛬

#324 [FEAT] 스크랩 없는 경우 비마이플랜 추천 여행 일정 표시
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/ScrapListRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapRecommendAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
Labels: feat, 🛫승현🛬
