Repository TeamBeMyPlan/BeMyPlan-Android, pull requests merged in 2022-01, with the labels that each got.

#2 Chore/1
  .idea/.gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/co/kr/bemyplan/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/util/RetrofitUtil.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/network_security_config.xml
  app/src/test/java/co/kr/bemyplan/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: ✈️승현✈️, chore

#4 Feat/3
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/data/MainViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/FirstFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/FourthFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/SecondFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/ThirdFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/adapter/MainViewPagerAdapter.kt
  app/src/main/res/drawable/ic_android_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_fourth.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/menu/menu_bnv.xml
  app/src/main/res/values/strings.xml
Labels: feat, ✈️승현✈️

#15 Feature/9 after purchase
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/data/DailyContents.kt
  app/src/main/java/co/kr/bemyplan/data/Post.kt
  app/src/main/java/co/kr/bemyplan/data/Spot.kt
  app/src/main/java/co/kr/bemyplan/ui/main/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/ImageBindingAdapter.kt
  app/src/main/res/drawable/blue_circle.xml
  app/src/main/res/drawable/blue_dotted_line_horizontal.xml
  app/src/main/res/drawable/blue_dotted_line_vertical.xml
  app/src/main/res/drawable/btn_daily.xml
  app/src/main/res/drawable/btn_daily_text_color.xml
  app/src/main/res/drawable/grey_empty_box.xml
  app/src/main/res/drawable/ic_icn_arrow_forward.xml
  app/src/main/res/drawable/ic_icn_car.xml
  app/src/main/res/drawable/ic_icn_copy.xml
  app/src/main/res/drawable/ic_icn_public_transport.xml
  app/src/main/res/drawable/ic_icn_walk.xml
  app/src/main/res/drawable/ic_icon_arrow.xml
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/daily_contents_list.xml
  app/src/main/res/layout/daily_route_list.xml
  app/src/main/res/layout/fragment_daily_contents.xml
  app/src/main/res/layout/fragment_scrap.xml
Labels: layout, 💪🏻정훈💪🏻

#16 Feature/10
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/co/kr/bemyplan/data/TempHomeData.kt
  app/src/main/java/co/kr/bemyplan/ui/main/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/adapter/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/adapter/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/util/ZoomOutPageTransformer.kt
  app/src/main/res/drawable-hdpi/img_home_editor.png
  app/src/main/res/drawable-hdpi/img_home_popular.png
  app/src/main/res/drawable-hdpi/img_home_recent.png
  app/src/main/res/drawable-mdpi/img_home_editor.png
  app/src/main/res/drawable-mdpi/img_home_popular.png
  app/src/main/res/drawable-mdpi/img_home_recent.png
  app/src/main/res/drawable-xhdpi/img_home_editor.png
  app/src/main/res/drawable-xhdpi/img_home_popular.png
  app/src/main/res/drawable-xhdpi/img_home_recent.png
  app/src/main/res/drawable-xxhdpi/img_home_editor.png
  app/src/main/res/drawable-xxhdpi/img_home_popular.png
  app/src/main/res/drawable-xxhdpi/img_home_recent.png
  app/src/main/res/drawable-xxxhdpi/img_home_editor.png
  app/src/main/res/drawable-xxxhdpi/img_home_popular.png
  app/src/main/res/drawable-xxxhdpi/img_home_recent.png
  app/src/main/res/drawable/ic_icn_more.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_plan.xml
  app/src/main/res/layout/item_popular.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 📸용민🎬

#18 Feature/14
  app/src/main/ic_bemyplan-playstore.png
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/SortFragment.kt
  app/src/main/res/drawable-hdpi/icn_check.png
  app/src/main/res/drawable-mdpi/icn_check.png
  app/src/main/res/drawable-xhdpi/icn_check.png
  app/src/main/res/drawable-xxhdpi/icn_check.png
  app/src/main/res/drawable-xxxhdpi/icn_check.png
  app/src/main/res/drawable/rectangle_white_top_radius_5.xml
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/dialog_sort.xml
  app/src/main/res/layout/fragment_sort.xml
  app/src/main/res/mipmap-hdpi/ic_bemyplan.png
  app/src/main/res/mipmap-hdpi/ic_bemyplan_foreground.png
  app/src/main/res/mipmap-hdpi/ic_bemyplan_round.png
  app/src/main/res/mipmap-mdpi/ic_bemyplan.png
  app/src/main/res/mipmap-mdpi/ic_bemyplan_foreground.png
  app/src/main/res/mipmap-mdpi/ic_bemyplan_round.png
  app/src/main/res/mipmap-xhdpi/ic_bemyplan.png
  app/src/main/res/mipmap-xhdpi/ic_bemyplan_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_bemyplan_round.png
  app/src/main/res/mipmap-xxhdpi/ic_bemyplan.png
  app/src/main/res/mipmap-xxhdpi/ic_bemyplan_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_bemyplan_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_bemyplan.png
  app/src/main/res/mipmap-xxxhdpi/ic_bemyplan_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_bemyplan_round.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat, ✈️승현✈️, layout

#25 Feature/17 after purchase recycler
  app/src/main/java/co/kr/bemyplan/data/Spot.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/daily_contents_list.xml
  app/src/main/res/layout/fragment_daily_contents.xml
  app/src/main/res/layout/item_daily_contents.xml
  app/src/main/res/layout/item_daily_route.xml
Labels: feat, 💪🏻정훈💪🏻

#27 Feature/24
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/login/LoginActivity.kt
  app/src/main/res/drawable-hdpi/btn_kakao.png
  app/src/main/res/drawable-hdpi/btn_look.png
  app/src/main/res/drawable-hdpi/icon_google.png
  app/src/main/res/drawable-hdpi/icon_kakao.png
  app/src/main/res/drawable-hdpi/img_logo_eg.png
  app/src/main/res/drawable-mdpi/btn_kakao.png
  app/src/main/res/drawable-mdpi/btn_look.png
  app/src/main/res/drawable-mdpi/icon_google.png
  app/src/main/res/drawable-mdpi/icon_kakao.png
  app/src/main/res/drawable-mdpi/img_logo_eg.png
  app/src/main/res/drawable-xhdpi/btn_kakao.png
  app/src/main/res/drawable-xhdpi/btn_look.png
  app/src/main/res/drawable-xhdpi/icon_google.png
  app/src/main/res/drawable-xhdpi/icon_kakao.png
  app/src/main/res/drawable-xhdpi/img_logo_eg.png
  app/src/main/res/drawable-xxhdpi/btn_kakao.png
  app/src/main/res/drawable-xxhdpi/btn_look.png
  app/src/main/res/drawable-xxhdpi/icon_google.png
  app/src/main/res/drawable-xxhdpi/icon_kakao.png
  app/src/main/res/drawable-xxhdpi/img_logo_eg.png
  app/src/main/res/drawable-xxxhdpi/btn_kakao.png
  app/src/main/res/drawable-xxxhdpi/btn_look.png
  app/src/main/res/drawable-xxxhdpi/icon_google.png
  app/src/main/res/drawable-xxxhdpi/icon_kakao.png
  app/src/main/res/drawable-xxxhdpi/img_logo_eg.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, ✈️승현✈️, layout

#29 Feature/20 location
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/co/kr/bemyplan/data/home/TempHomeData.kt
  app/src/main/java/co/kr/bemyplan/data/location/LocationData.kt
  app/src/main/java/co/kr/bemyplan/ui/main/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/HorizontalItemDecorator.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/VerticalItemDecorator.kt
  app/src/main/res/drawable-hdpi/img_busan.png
  app/src/main/res/drawable-hdpi/img_gangneung.png
  app/src/main/res/drawable-mdpi/img_busan.png
  app/src/main/res/drawable-mdpi/img_gangneung.png
  app/src/main/res/drawable-xhdpi/img_busan.png
  app/src/main/res/drawable-xhdpi/img_gangneung.png
  app/src/main/res/drawable-xxhdpi/img_busan.png
  app/src/main/res/drawable-xxhdpi/img_gangneung.png
  app/src/main/res/drawable-xxxhdpi/img_busan.png
  app/src/main/res/drawable-xxxhdpi/img_gangneung.png
  app/src/main/res/drawable/drawable-hdpi/img_busan.png
  app/src/main/res/drawable/drawable-hdpi/img_yeosu.png
  app/src/main/res/drawable/drawable-mdpi/img_busan.png
  app/src/main/res/drawable/drawable-mdpi/img_yeosu.png
  app/src/main/res/drawable/drawable-xhdpi/img_busan.png
  app/src/main/res/drawable/drawable-xhdpi/img_yeosu.png
  app/src/main/res/drawable/drawable-xxhdpi/img_busan.png
  app/src/main/res/drawable/drawable-xxhdpi/img_yeosu.png
  app/src/main/res/drawable/drawable-xxxhdpi/img_busan.png
  app/src/main/res/drawable/drawable-xxxhdpi/img_yeosu.png
  app/src/main/res/drawable/ic_img_layer.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_location.xml
  app/src/main/res/layout/item_location.xml
  app/src/main/res/layout/item_popular.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feat, layout, 📸용민🎬

#31 Feature/26 refector
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/data/DailyContents.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DayAdapter.kt
  app/src/main/res/drawable/btn_daily.xml
  app/src/main/res/drawable/circle_blue.xml
  app/src/main/res/drawable/dotted_line_blue_horizontal.xml
  app/src/main/res/drawable/dotted_line_blue_vertical.xml
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/item_daily_route.xml
  app/src/main/res/layout/item_day_button.xml
Labels: feat, chore, layout, 💪🏻정훈💪🏻

#33 [FEAT] #20 - home viewpager ratio 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
Labels: feat, 📸용민🎬

#34 Feature/32 myplan
  app/src/main/java/co/kr/bemyplan/data/myplan/Profile.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MyPageFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/res/drawable/ic_icn_settings.xml
  app/src/main/res/drawable/ic_img_profile.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_plan.xml
Labels: feat, layout, 💪🏻정훈💪🏻

#36 Feature/28
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/util/CustomDialog.kt
  app/src/main/res/drawable-hdpi/background.png
  app/src/main/res/drawable-hdpi/btn_agree_off.png
  app/src/main/res/drawable-hdpi/btn_start_inactive.png
  app/src/main/res/drawable-hdpi/icn_clear.png
  app/src/main/res/drawable-hdpi/textbox.png
  app/src/main/res/drawable-mdpi/background.png
  app/src/main/res/drawable-mdpi/btn_agree_off.png
  app/src/main/res/drawable-mdpi/btn_start_inactive.png
  app/src/main/res/drawable-mdpi/icn_clear.png
  app/src/main/res/drawable-mdpi/textbox.png
  app/src/main/res/drawable-xhdpi/background.png
  app/src/main/res/drawable-xhdpi/btn_agree_off.png
  app/src/main/res/drawable-xhdpi/btn_start_inactive.png
  app/src/main/res/drawable-xhdpi/icn_clear.png
  app/src/main/res/drawable-xhdpi/textbox.png
  app/src/main/res/drawable-xxhdpi/background.png
  app/src/main/res/drawable-xxhdpi/btn_agree_off.png
  app/src/main/res/drawable-xxhdpi/btn_start_inactive.png
  app/src/main/res/drawable-xxhdpi/icn_clear.png
  app/src/main/res/drawable-xxhdpi/textbox.png
  app/src/main/res/drawable-xxxhdpi/background.png
  app/src/main/res/drawable-xxxhdpi/btn_agree_off.png
  app/src/main/res/drawable-xxxhdpi/btn_start_inactive.png
  app/src/main/res/drawable-xxxhdpi/icn_clear.png
  app/src/main/res/drawable-xxxhdpi/textbox.png
  app/src/main/res/drawable/circle_border.xml
  app/src/main/res/drawable/inset_horizontal_24.xml
  app/src/main/res/drawable/rectangle_border_red_radius_5.xml
  app/src/main/res/drawable/rectangle_white_radius_5.xml
  app/src/main/res/drawable/selector_terms.xml
  app/src/main/res/layout/dialog_yes_no.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: feat, ✈️승현✈️, layout

#38 Feature/35 myplan purchase things
  app/src/main/java/co/kr/bemyplan/data/myplan/PurchaseTour.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/exist/ExistMyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/exist/adapter/ExistMyPlanAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/res/layout/fragment_exist_my_plan.xml
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/item_my_plan_purchase_list.xml
Labels: feat, layout, 💪🏻정훈💪🏻

#42 Feature/30 charging
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/res/color/selector_blue0077b0_313740.xml
  app/src/main/res/color/selector_blue0077b0_greycdb0d7.xml
  app/src/main/res/drawable-hdpi/img.png
  app/src/main/res/drawable-hdpi/img_charge.png
  app/src/main/res/drawable-mdpi/img.png
  app/src/main/res/drawable-mdpi/img_charge.png
  app/src/main/res/drawable-xhdpi/img.png
  app/src/main/res/drawable-xhdpi/img_charge.png
  app/src/main/res/drawable-xxhdpi/img.png
  app/src/main/res/drawable-xxhdpi/img_charge.png
  app/src/main/res/drawable-xxxhdpi/icn_clear.png
  app/src/main/res/drawable-xxxhdpi/img.png
  app/src/main/res/drawable-xxxhdpi/img_charge.png
  app/src/main/res/drawable/ic_icn_done.xml
  app/src/main/res/drawable/rectangle_selector_blue_grey_radius_5.xml
  app/src/main/res/layout/activity_purchase.xml
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/values/strings.xml
Labels: feat, layout, 📸용민🎬

#43 Feature/37
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/util/CustomDialog.kt
  app/src/main/java/co/kr/bemyplan/util/SingleLiveEvent.kt
  app/src/main/res/layout/dialog_yes_no.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: feat, ✈️승현✈️, layout

#47 Feature/41 settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/empty/EmptyMyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/exist/ExistMyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/withdrawal/WithdrawalActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/util/ImageRadius.kt
  app/src/main/res/drawable/ic_icn_info.xml
  app/src/main/res/drawable/ic_icn_qna.xml
  app/src/main/res/drawable/ic_icn_upload.xml
  app/src/main/res/drawable/rectangle_border_radius_5.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/fragment_empty_my_plan.xml
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/item_daily_contents.xml
Labels: feat, layout, 💪🏻정훈💪🏻

#49 Feature/48 withdrawal scrollview
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/withdrawal/WithdrawalActivity.kt
  app/src/main/java/co/kr/bemyplan/util/ImageRadius.kt
  app/src/main/res/drawable/rectangle_blue_radius_5.xml
  app/src/main/res/drawable/rectangle_grey_radius_5.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/fragment_empty_my_plan.xml
  app/src/main/res/layout/fragment_exist_my_plan.xml
Labels: chore, 💪🏻정훈💪🏻

#51 Feature/45
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/application/MainApplication.kt
  app/src/main/java/co/kr/bemyplan/data/local/AutoLoginData.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/values-night/themes.xml
  settings.gradle
Labels: feat, ✈️승현✈️

#54 Feature/53
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/ContentViewPagerAdapter.kt
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/item_list_content.xml
Labels: feat, ✈️승현✈️, layout, refactor

#55 Feature/50 after purchase
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DayAdapter.kt
  app/src/main/java/co/kr/bemyplan/util/ToastMessage.kt
  app/src/main/res/color/selector_chip.xml
  app/src/main/res/drawable/btn_daily.xml
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/item_daily_contents.xml
  app/src/main/res/layout/item_day_button.xml
  app/src/main/res/values/themes.xml
Labels: chore, 💪🏻정훈💪🏻

#59 [FEAT] 더보기, 접기 추가
  app/src/main/java/co/kr/bemyplan/data/Spot.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DayAdapter.kt
  app/src/main/res/drawable/ic_icn_arrow_down.xml
  app/src/main/res/drawable/ic_icn_arrow_up.xml
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/fragment_daily_contents.xml
Labels: feat, 💪🏻정훈💪🏻

#61 Feature/58
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/DailyContents.kt
  app/src/main/java/co/kr/bemyplan/data/entity/Post.kt
  app/src/main/java/co/kr/bemyplan/data/entity/Spot.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/local/AutoLoginData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/TempHomeData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/location/LocationData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/Profile.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/PurchaseTour.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/SummaryModel.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/adapter/ListAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapRecommendAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/ContentAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/ContentViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/SummaryAdapter.kt
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/item_before_purchase_content.xml
  app/src/main/res/layout/item_before_purchase_summary.xml
  app/src/main/res/layout/item_daily_contents.xml
  app/src/main/res/layout/item_daily_route.xml
  app/src/main/res/layout/item_day_button.xml
  app/src/main/res/layout/item_list_content.xml
  app/src/main/res/layout/item_my_plan_purchase_list.xml
  app/src/main/res/layout/item_scrap_content.xml
  app/src/main/res/layout/item_scrap_empty_content.xml
Labels: feat, ✈️승현✈️, refactor

#63 Feature/46 databinding
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/login/LoginActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/java/co/kr/bemyplan/util/BindingAdapter1.kt
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/layout/fragment_location.xml
  app/src/main/res/layout/item_home_plan.xml
  app/src/main/res/layout/item_location.xml
  app/src/main/res/layout/item_popular.xml
  app/src/main/res/values/dimens.xml
Labels: feat, layout, 📸용민🎬

#65 Feature/64 home popular server
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/HomePopularService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/ResponseHomePopularData.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_popular.xml
Labels: feat, layout, 📸용민🎬

#66 Feature/60 myplan dialog
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/withdrawal/WithdrawalActivity.kt
  app/src/main/java/co/kr/bemyplan/util/CustomDialog.kt
  app/src/main/res/layout/dialog_yes.xml
  app/src/main/res/layout/dialog_yes_no_with_title.xml
Labels: feat, 💪🏻정훈💪🏻

#67 Feature/57
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseScrapList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ScrapListService.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/java/co/kr/bemyplan/util/BindingAdapter1.kt
  app/src/main/res/layout/item_scrap_content.xml
  app/src/main/res/layout/item_scrap_empty_content.xml
Labels: feat, ✈️승현✈️

#69 Feature/62
  app/src/main/res/drawable-hdpi/icn_check.png
  app/src/main/res/drawable-mdpi/icn_check.png
  app/src/main/res/drawable-xhdpi/icn_check.png
  app/src/main/res/drawable-xxhdpi/icn_check.png
  app/src/main/res/drawable-xxxhdpi/icn_check.png
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/values/strings.xml
Labels: ✈️승현✈️, layout

#71 Feature/70
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/NewListService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseNewList.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/NewListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/NewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/res/layout/item_list_content.xml
Labels: feat, ✈️승현✈️

#76 Feature/75
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LocationListService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseLocationList.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/LocationListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/LocationListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
Labels: feat, ✈️승현✈️

#78 Feature/68 after purchase photo
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/DailyContents.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/Post.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/Spot.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/PhotoViewPagerAdapter.kt
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/item_after_purchase_photo.xml
  app/src/main/res/layout/item_daily_contents.xml
  app/src/main/res/layout/item_daily_route.xml
  app/src/main/res/layout/item_day_button.xml
Labels: feat, 💪🏻정훈💪🏻

#80 Feature/77
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/UserPostListService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseUserPostList.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/UserPostListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/UserPostListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
Labels: feat, ✈️승현✈️

#81 Feature/73 location server
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/HomePopularService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LocationService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/location/ResponseLocationData.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationViewModel.kt
  app/src/main/res/layout/item_location.xml
Labels: feat, layout, 📸용민🎬

#83 [FEAT] #73 - 여행지 잠김여부에 따른 클릭
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/res/layout/item_location.xml
Labels: feat, layout, 📸용민🎬

#84 Feature/82
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PreviewInfoService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PreviewListService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/PreviewInfoModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ResponsePreviewInfo.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ResponsePreviewList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/SummaryModel.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/PreviewInfoRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/PreviewInfoRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/PreviewListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/PreviewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/SummaryAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforePurchaseViewModel.kt
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/item_before_purchase_content.xml
  app/src/main/res/layout/item_before_purchase_summary.xml
Labels: feat, ✈️승현✈️

#86 Feature/85
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseScrapList.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/SortFragment.kt
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/dialog_sort.xml
  app/src/main/res/layout/item_scrap_content.xml
Labels: feat, ✈️승현✈️, refactor

#88 Feature/87
  app/src/main/java/co/kr/bemyplan/data/repository/list/NewListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/NewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/location/LocationListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/location/LocationListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewInfoRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewInfoRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/suggest/SuggestListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/suggest/SuggestListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/userpost/UserPostListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/userpost/UserPostListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
Labels: ✈️승현✈️, refactor

#91 Feature/79 after purchase server
  app/src/main/java/co/kr/bemyplan/data/api/AfterPostService.kt
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseSuggestList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/DailyContents.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/Post.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/ResponseAfterPost.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/Spot.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/fragment_daily_contents.xml
  app/src/main/res/layout/item_daily_contents.xml
  app/src/main/res/layout/item_daily_route.xml
  app/src/main/res/layout/item_day_button.xml
Labels: feat, 💪🏻정훈💪🏻

#93 Feature/90
  app/src/main/java/co/kr/bemyplan/data/repository/list/new/NewListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/new/NewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
Labels: feat, ✈️승현✈️

#95 Feature/89
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/MyPlanService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/MyModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/ResponseMyPlan.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/myplan/MyPlanRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/myplan/MyPlanRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/res/layout/fragment_my_plan.xml
  app/src/main/res/layout/item_my_plan_purchase_list.xml
Labels: feat, ✈️승현✈️, layout

#97 Feature/96
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/java/co/kr/bemyplan/util/BindingAdapter1.kt
Labels: feat, ✈️승현✈️

#99 Feature/98
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
Labels: feat, ✈️승현✈️

#101 [FEAT] #100 - 여행 크리에이터 신청 뷰 완성
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/creator/CreatorProposeActivity.kt
  app/src/main/res/drawable-hdpi/icn_1.png
  app/src/main/res/drawable-hdpi/icn_2.png
  app/src/main/res/drawable-hdpi/icn_3.png
  app/src/main/res/drawable-hdpi/icn_4.png
  app/src/main/res/drawable-hdpi/icn_5.png
  app/src/main/res/drawable-hdpi/icn_6.png
  app/src/main/res/drawable-mdpi/icn_1.png
  app/src/main/res/drawable-mdpi/icn_2.png
  app/src/main/res/drawable-mdpi/icn_3.png
  app/src/main/res/drawable-mdpi/icn_4.png
  app/src/main/res/drawable-mdpi/icn_5.png
  app/src/main/res/drawable-mdpi/icn_6.png
  app/src/main/res/drawable-xhdpi/icn_1.png
  app/src/main/res/drawable-xhdpi/icn_2.png
  app/src/main/res/drawable-xhdpi/icn_3.png
  app/src/main/res/drawable-xhdpi/icn_4.png
  app/src/main/res/drawable-xhdpi/icn_5.png
  app/src/main/res/drawable-xhdpi/icn_6.png
  app/src/main/res/drawable-xxhdpi/icn_1.png
  app/src/main/res/drawable-xxhdpi/icn_2.png
  app/src/main/res/drawable-xxhdpi/icn_3.png
  app/src/main/res/drawable-xxhdpi/icn_4.png
  app/src/main/res/drawable-xxhdpi/icn_5.png
  app/src/main/res/drawable-xxhdpi/icn_6.png
  app/src/main/res/drawable-xxxhdpi/icn_1.png
  app/src/main/res/drawable-xxxhdpi/icn_2.png
  app/src/main/res/drawable-xxxhdpi/icn_3.png
  app/src/main/res/drawable-xxxhdpi/icn_4.png
  app/src/main/res/drawable-xxxhdpi/icn_5.png
  app/src/main/res/drawable-xxxhdpi/icn_6.png
  app/src/main/res/layout/activity_creator_propose.xml
Labels: feat, layout, 💪🏻정훈💪🏻

#103 Feature/102
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
Labels: feat, ✈️승현✈️

#105 Feature/104
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
Labels: feat, ✈️승현✈️

#107 [REFECTOR] #106 - 터치영역 조정
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/res/layout/activity_settings.xml
Labels: layout, 💪🏻정훈💪🏻, refactor

#110 Feature/108
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/Post.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/example/ExampleDummy.kt
  app/src/main/res/layout/item_daily_contents.xml
Labels: feat, layout, 💪🏻정훈💪🏻

#112 [FEAT] #111 - 문의하기 추가
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
Labels: feat, 💪🏻정훈💪🏻

#113 FEAT/109
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
Labels: feat, ✈️승현✈️

#116 Feature/94 home newplan
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/HomeNewService.kt
  app/src/main/java/co/kr/bemyplan/data/api/HomeSuggestService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/ResponseHomeData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/ResponseHomePopularData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/TempHomeData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/location/LocationData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/location/ResponseLocationData.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/res/drawable/ic_img_logo_name.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_plan.xml
  app/src/main/res/layout/item_location.xml
  app/src/main/res/values/themes.xml
Labels: feat, 📸용민🎬

#117 Feature/92 map
  app/drawable-hdpi/icn_subpin_select.png
  app/drawable-mdpi/icn_subpin_select.png
  app/drawable-xhdpi/icn_subpin_select.png
  app/drawable-xxhdpi/icn_subpin_select.png
  app/drawable-xxxhdpi/icn_subpin_select.png
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/Post.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/ResponseAfterPost.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/after/Spot.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/example/ExampleDummy.kt
  app/src/main/res/drawable-hdpi/icn_mainpin_select.png
  app/src/main/res/drawable-hdpi/icn_mainpin_select_pick.png
  app/src/main/res/drawable-hdpi/icn_subpin_select.png
  app/src/main/res/drawable-mdpi/icn_mainpin_select.png
  app/src/main/res/drawable-mdpi/icn_mainpin_select_pick.png
  app/src/main/res/drawable-mdpi/icn_subpin_select.png
  app/src/main/res/drawable-xhdpi/icn_mainpin_select.png
  app/src/main/res/drawable-xhdpi/icn_mainpin_select_pick.png
  app/src/main/res/drawable-xhdpi/icn_subpin_select.png
  app/src/main/res/drawable-xxhdpi/icn_mainpin_select.png
  app/src/main/res/drawable-xxhdpi/icn_mainpin_select_pick.png
  app/src/main/res/drawable-xxhdpi/icn_subpin_select.png
  app/src/main/res/drawable-xxxhdpi/icn_mainpin_select.png
  app/src/main/res/drawable-xxxhdpi/icn_mainpin_select_pick.png
  app/src/main/res/drawable-xxxhdpi/icn_subpin_select.png
  app/src/main/res/layout/card_balloon.xml
  app/src/main/res/layout/fragment_daily_contents.xml
  app/src/main/res/layout/item_daily_contents.xml
  app/src/main/res/layout/item_daily_route.xml
Labels: feat, 💪🏻정훈💪🏻

#119 Feature/114
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/EmptyScrapListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/UserPostListService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/ResponseMyPlan.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseEmptyScrapList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseScrapList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/PreviewInfoModel.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/userpost/UserPostListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/userpost/UserPostListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/EmptyScrapListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/EmptyScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/adapter/ListAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapRecommendAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/ContentAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/SortFragment.kt
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/layout/item_before_purchase_content.xml
  app/src/main/res/layout/item_list_content.xml
  app/src/main/res/layout/item_scrap_content.xml
  app/src/main/res/layout/item_scrap_empty_content.xml
Labels: feat, ✈️승현✈️, refactor

#122 Feature/120
  app/src/main/java/co/kr/bemyplan/data/entity/list/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/MyModel.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/util/BindingAdapter1.kt
  app/src/main/res/layout/item_list_content.xml
Labels: feat, ✈️승현✈️, refactor

#123 Feature/121 merge
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ChargingData.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/res/color/selector_blue0077b0_313740.xml
  app/src/main/res/color/selector_blue0077b0_greycdb0d7.xml
  app/src/main/res/drawable/rectangle_border_blue_radius_5.xml
  app/src/main/res/drawable/rectangle_border_grey_radius_5.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_sign_up.xml
Labels: 📸용민🎬

#126 Feature/118 afterpurchase server
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/fragment_daily_contents.xml
Labels: feat, 💪🏻정훈💪🏻, connect server

#127 [FEAT] #124 - charging, charged 기능 구현
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ChargingData.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/layout/fragment_location.xml
Labels: 📸용민🎬

#129 Feature/128
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/fragment_my_plan.xml
Labels: chore, layout, 💪🏻정훈💪🏻

#131 Feature/125
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LoginService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/local/AutoLoginData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/RequestLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/ResponseLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/UserInfoModel.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/fragment_before_charging.xml
Labels: feat, ✈️승현✈️

#134 [DOCS] #130 - README.md update
  README.md
Labels: documentation, 💪🏻정훈💪🏻

#136 Feature/135
  app/src/main/java/co/kr/bemyplan/data/repository/list/location/LocationListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewInfoRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/suggest/SuggestListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/userpost/UserPostListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/EmptyScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
Labels: feat

#138 [BUG] #137 - visibility 추가
  app/src/main/res/layout/fragment_my_plan.xml
Labels: bug, layout, 💪🏻정훈💪🏻

#141 Feature/139
  app/src/main/java/co/kr/bemyplan/ui/login/LoginActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
Labels: feat, ✈️승현✈️

#143 Feature/140
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/WithdrawService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/RequestWithdraw.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/ResponseWithdraw.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/withdrawal/WithdrawalActivity.kt
Labels: feat, 💪🏻정훈💪🏻, connect server

#146 Feature/145 design change
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/res/layout/activity_settings.xml
Labels: chore, 💪🏻정훈💪🏻

#148 Feature/147
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/res/layout/fragment_daily_contents.xml
Labels: bug, 💪🏻정훈💪🏻

#149 Feature/142
  app/src/main/java/co/kr/bemyplan/data/api/LocationListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/MyPlanService.kt
  app/src/main/java/co/kr/bemyplan/data/api/NewListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PreviewInfoService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PreviewListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/ScrapListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/SuggestListService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/MyModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/PreviewInfoModel.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/new/NewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewInfoRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewInfoRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/suggest/SuggestListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/myplan/MyPlanRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/myplan/MyPlanRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/adapter/ListAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/item_before_purchase_content.xml
  app/src/main/res/layout/item_list_content.xml
  app/src/main/res/layout/item_my_plan_purchase_list.xml
  app/src/main/res/layout/item_scrap_content.xml
  app/src/main/res/layout/item_scrap_empty_content.xml
Labels: feat, ✈️승현✈️

#152 [FEAT] #144 - 홈 탭에서 모든걸 넘겨주는 작업 완료
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/ResponseHomeData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/home/ResponseHomePopularData.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feat, layout, 📸용민🎬

#154 Feature/151
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/res/layout/fragment_before_charging.xml
Labels: feat, ✈️승현✈️

#155 Feature/150 map
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/res/layout/fragment_daily_contents.xml
  app/src/main/res/layout/fragment_my_plan.xml
Labels: chore, 💪🏻정훈💪🏻

#157 Feature/156
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
  app/src/main/res/layout/activity_after_purchase.xml
  app/src/main/res/layout/item_my_plan_purchase_list.xml
Labels: chore, 💪🏻정훈💪🏻

#158 [FEAT] #153 - splash
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/res/drawable/ic_img_logo_eg.xml
  app/src/main/res/layout/activity_splash.xml
Labels: feat, layout, 📸용민🎬

#159 [FEAT] #133 - 끝
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PostScrapService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseScrap.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/PostScrapRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/PostScrapRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/res/layout/fragment_before_charging.xml
Labels: feat, ✈️승현✈️

#161 [CHORE] #160 - 더미데이터인 경우 터치 리스너 제외
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
Labels: chore, 💪🏻정훈💪🏻

#163 Feature/162
  app/src/main/res/layout/item_after_purchase_photo.xml
Labels: chore, 💪🏻정훈💪🏻

#166 Feature/164
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/SortFragment.kt
  app/src/main/res/layout/activity_purchase.xml
Labels: ✈️승현✈️, refactor

#167 Feature/164
  app/src/main/java/co/kr/bemyplan/ui/list/adapter/ListAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapRecommendAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/ContentViewPagerAdapter.kt
Labels: ✈️승현✈️, refactor

#168 [FEAT] #164 - ViewModel 미사용 코드 및 불필요 Log 제거
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
Labels: ✈️승현✈️, refactor

#170 [FEAT] #169 - BaseActivity, BaseFragment 구현 및 적용
  app/src/main/java/co/kr/bemyplan/ui/base/BaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/base/BaseFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
Labels: feat, ✈️승현✈️, refactor

#171 Feature/132
  app/src/main/java/co/kr/bemyplan/data/api/LoginService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/check/RequestDuplicatedNickname.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/check/ResponseDuplicatedNickname.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
Labels: feat, ✈️승현✈️

#174 Feature/172
  app/src/main/java/co/kr/bemyplan/data/api/LoginService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/local/AutoLoginData.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/ResponseLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/login/RequestLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/login/ResponseLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/signup/RequestSignUp.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/signup/ResponseSignUp.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/res/layout/fragment_my_plan.xml
Labels: feat, ✈️승현✈️

#176 Feature/175
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/application/MainApplication.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/preview/PreviewInfoRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PreviewInfoRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PreviewInfoRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PreviewListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PreviewListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RetrofitModule.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  build.gradle
Labels: feat, ✈️승현✈️

#178 [CHORE] #177 - 잘못된 지도 핀 제거
  app/drawable-hdpi/icn_subpin_select.png
  app/drawable-mdpi/icn_subpin_select.png
  app/drawable-xhdpi/icn_subpin_select.png
  app/drawable-xxhdpi/icn_subpin_select.png
  app/drawable-xxxhdpi/icn_subpin_select.png
Labels: chore, 💪🏻정훈💪🏻
