Repository TeamBeMyPlan/BeMyPlan-Android, pull requests merged in 2022-05, with the labels that each got.

#250 Feat/249
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/application/MainApplication.kt
  app/src/main/java/co/kr/bemyplan/data/api/GoogleLoginService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LoginService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/check/RequestDuplicatedNickname.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/check/ResponseDuplicatedNickname.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/login/RequestGoogleLogin.kt
  app/src/main/java/co/kr/bemyplan/data/entity/login/login/ResponseGoogleLogin.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/GoogleLoginRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/login/LoginRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/CoroutineModule.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/di/RetrofitModule.kt
  app/src/main/java/co/kr/bemyplan/di/ServiceModule.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/GoogleLoginRepository.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/LoginRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/SignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckNicknameFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckTermsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/settings/SettingsActivity.kt
Labels: feat, ✈️승현✈️

#252 Feat/251
  app/src/main/java/co/kr/bemyplan/data/api/LocationListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LocationService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseLatestList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseLocationList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseSuggestList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseUserPostList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseEmptyScrapList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseScrapList.kt
  app/src/main/java/co/kr/bemyplan/data/interceptor/AuthInterceptor.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/location/LocationListRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/location/LocationListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/domain/model/list/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/domain/model/list/PlanList.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/LocationListRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/adapter/ListAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapRecommendAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/viewmodel/SortViewModel.kt
  app/src/main/java/co/kr/bemyplan/util/BindingAdapter.kt
  app/src/main/java/co/kr/bemyplan/util/ImageRadius.kt
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/item_list_content.xml
  app/src/main/res/layout/item_scrap_content.xml
  app/src/main/res/layout/item_scrap_empty_content.xml
Labels: feat, ✈️승현✈️

#254 Feat/253
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/co/kr/bemyplan/data/api/LocationListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/PreviewService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ContentModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/PreviewInfoModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ResponsePreviewInfo.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ResponsePreviewList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ResponsePreviewPlan.kt
  app/src/main/java/co/kr/bemyplan/data/repository/list/location/LocationListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PreviewRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PreviewRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewContents.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewInfo.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewPlan.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/LocationListRepository.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/PreviewRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/ContentAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/SortFragment.kt
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/layout/item_before_purchase_content.xml
  app/src/main/res/values/strings.xml
Labels: feat, ✈️승현✈️

#256 [FEAT] #246 - 여행지뷰 서버연결!
  app/src/main/java/co/kr/bemyplan/data/api/ApiService.kt
  app/src/main/java/co/kr/bemyplan/data/api/LocationService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/location/ResponseLocationData.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/location/LocationRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/di/ServiceModule.kt
  app/src/main/java/co/kr/bemyplan/domain/model/main/location/LocationData.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/LocationRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/res/layout/item_location.xml
Labels: feat, 📸용민🎬

#261 [FEAT] #260 - 구매(결제) API 연결
  app/src/main/java/co/kr/bemyplan/data/api/PurchaseService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/RequestPurchase.kt
  app/src/main/java/co/kr/bemyplan/data/entity/purchase/before/ResponsePurchase.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PurchaseRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/di/ServiceModule.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/PurchaseRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargedFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
Labels: feat, ✈️승현✈️

#266 Fix/265
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/preview/PreviewRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewContents.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewPlan.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/res/layout/item_popular.xml
  app/src/main/res/values/strings.xml
Labels: bug, ✈️승현✈️

#267 #259 [FEAT] 스크랩 관련 API 연결
  app/src/main/java/co/kr/bemyplan/data/api/PostScrapService.kt
  app/src/main/java/co/kr/bemyplan/data/api/ScrapListService.kt
  app/src/main/java/co/kr/bemyplan/data/api/ScrapService.kt
  app/src/main/java/co/kr/bemyplan/data/entity/list/ResponseLatestList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/MyModel.kt
  app/src/main/java/co/kr/bemyplan/data/entity/main/scrap/ResponseScrapList.kt
  app/src/main/java/co/kr/bemyplan/data/entity/scrap/ResponseScrap.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapListRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/main/scrap/ScrapRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/scrap/PostScrapRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/scrap/PostScrapRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/data/repository/scrap/ScrapRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RepositoryModule.kt
  app/src/main/java/co/kr/bemyplan/di/ServiceModule.kt
  app/src/main/java/co/kr/bemyplan/domain/model/purchase/before/PreviewInfo.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/LoginRepository.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/ScrapListRepository.kt
  app/src/main/java/co/kr/bemyplan/domain/repository/ScrapRepository.kt
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/adapter/ListAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/adapter/ScrapAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/PurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/java/co/kr/bemyplan/util/BindingAdapter.kt
  app/src/main/java/co/kr/bemyplan/util/TransExtension.kt
  app/src/main/res/layout/fragment_before_charging.xml
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/layout/item_before_purchase_content.xml
  app/src/main/res/layout/item_location.xml
Labels: bug, feat, ✈️승현✈️
