Repository TeamBeMyPlan/BeMyPlan-Android, pull requests merged in 2022-03, with the labels that each got.

#217 Feat/216
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckEmailFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/signup/CheckTermsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/fragment_check_email.xml
Labels: feat, ✈️승현✈️, refactor

#221 Refactor/220
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/login/OldSignUpFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/BeforeChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/adapter/ContentAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/viewmodel/BeforeChargingViewModel.kt
  app/src/main/res/layout/fragment_charged.xml
  app/src/main/res/layout/fragment_charging.xml
  app/src/main/res/layout/fragment_old_sign_up.xml
Labels: ✈️승현✈️, refactor

#223 Feature/212
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/location/LocationViewModel.kt
Labels: feat, 📸용민🎬

#224 Refactor/222
  app/src/main/java/co/kr/bemyplan/ui/list/ListActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/list/viewmodel/ListViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/MainActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/EmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/NotEmptyScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/ScrapFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/scrap/viewmodel/ScrapViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/SortFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/sort/viewmodel/SortViewModel.kt
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/fragment_not_empty_scrap.xml
Labels: feat, ✈️승현✈️, refactor

#225 #218 [FEAT] Firebase Analytics Setting
  .gitignore
  app/build.gradle
  app/src/main/java/co/kr/bemyplan/ui/login/LoginFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_sort.xml
  build.gradle
Labels: feat, ✈️승현✈️

#226 Feature/219
  .gitignore
  app/src/main/java/co/kr/bemyplan/data/api/AfterPostService.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/after/AfterPurchaseRepository.kt
  app/src/main/java/co/kr/bemyplan/data/repository/purchase/after/AfterPurchaseRepositoryImpl.kt
  app/src/main/java/co/kr/bemyplan/di/RetrofitModule.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/AfterPurchaseActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/DailyContentsFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/ImageViewActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/adapter/DailyContentsAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/viewmodel/AfterPurchaseViewModel.kt
  app/src/main/res/layout/activity_after_purchase.xml
Labels: feat, 💪🏻정훈💪🏻, MVVM

#229 [CHORE] #228 - 더미데이터 수정
  app/src/main/java/co/kr/bemyplan/ui/purchase/after/example/ExampleDummy.kt
Labels: chore, 💪🏻정훈💪🏻

#230 Feature/227 onboarding
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/main/home/HomeFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment1.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment2.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment3.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/ViewpagerFragmentAdapter.kt
  app/src/main/res/drawable-hdpi/onboarding1.png
  app/src/main/res/drawable-hdpi/onboarding2.png
  app/src/main/res/drawable-hdpi/onboarding3.png
  app/src/main/res/drawable-mdpi/onboarding1.png
  app/src/main/res/drawable-mdpi/onboarding2.png
  app/src/main/res/drawable-mdpi/onboarding3.png
  app/src/main/res/drawable-xhdpi/onboarding1.png
  app/src/main/res/drawable-xhdpi/onboarding2.png
  app/src/main/res/drawable-xhdpi/onboarding3.png
  app/src/main/res/drawable-xxhdpi/onboarding1.png
  app/src/main/res/drawable-xxhdpi/onboarding2.png
  app/src/main/res/drawable-xxhdpi/onboarding3.png
  app/src/main/res/drawable-xxxhdpi/onboarding1.png
  app/src/main/res/drawable-xxxhdpi/onboarding2.png
  app/src/main/res/drawable-xxxhdpi/onboarding3.png
  app/src/main/res/drawable/ic_dots_1.xml
  app/src/main/res/drawable/ic_dots_2.xml
  app/src/main/res/drawable/ic_dots_3.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding1.xml
  app/src/main/res/layout/fragment_onboarding2.xml
  app/src/main/res/layout/fragment_onboarding3.xml
  app/src/main/res/values/strings.xml
Labels: feat, layout, 📸용민🎬

#231 [FEAT] #227 - 온보딩 분기처리 성공, 이미지 비율 미완성
  app/src/main/java/co/kr/bemyplan/data/local/OnBoardingData.kt
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment3.kt
Labels: feat, layout, 📸용민🎬

#233 Feature/232
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment1.kt
Labels: bug, 💪🏻정훈💪🏻

#234 Feature/227 onboarding
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/bemyplan/application/MainApplication.kt
  app/src/main/java/co/kr/bemyplan/data/local/OnBoardingData.kt
  app/src/main/java/co/kr/bemyplan/data/local/OnboardingSharedpref.kt
  app/src/main/java/co/kr/bemyplan/ui/main/SplashActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment1.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment2.kt
  app/src/main/java/co/kr/bemyplan/ui/onboarding/OnboardingFragment3.kt
  app/src/main/res/drawable-hdpi/img_onboarding_01.png
  app/src/main/res/drawable-hdpi/onboarding1.png
  app/src/main/res/drawable-mdpi/img_onboarding_01.png
  app/src/main/res/drawable-mdpi/onboarding1.png
  app/src/main/res/drawable-xhdpi/img_onboarding_01.png
  app/src/main/res/drawable-xhdpi/onboarding1.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_01.png
  app/src/main/res/drawable-xxhdpi/onboarding1.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_01.png
  app/src/main/res/drawable-xxxhdpi/onboarding1.png
  app/src/main/res/layout/fragment_onboarding1.xml
  app/src/main/res/layout/fragment_onboarding2.xml
  app/src/main/res/layout/fragment_onboarding3.xml
  app/src/main/res/values/strings.xml
Labels: feat, layout, 📸용민🎬

#236 [FEAT] #235 zero event dialog compelete
  app/src/main/java/co/kr/bemyplan/ui/purchase/before/ChargingFragment.kt
  app/src/main/java/co/kr/bemyplan/util/CustomDialog.kt
  app/src/main/res/layout/dialog_yes_zero_event.xml
  app/src/main/res/values/strings.xml
Labels: feat, layout, 📸용민🎬

#242 Feat/241
  app/src/main/java/co/kr/bemyplan/data/entity/main/myplan/MyModel.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/MyPlanFragment.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/adapter/MyPlanAdapter.kt
  app/src/main/java/co/kr/bemyplan/ui/main/myplan/viewmodel/MyPlanViewModel.kt
  app/src/main/res/layout/item_list_content.xml
  app/src/main/res/layout/item_my_plan_purchase_list.xml
Labels: feat, ✈️승현✈️
